spring:
  devtools:
    add-properties: true

logging:
  level:
    web: INFO
    com.microservices.app.item: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
