logging:
  level:
    com.microservices: DEBUG
    org.springframework.cloud.gateway: ERROR
    org.springframework.http.server.reactive: ERROR
    org.springframework.web.reactive: ERROR
    reactor.ipc.netty: ERROR
    reactor.netty.http.client.HttpClientConnect: ERROR
