hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/v1/items/**
          filters:
            - StripPrefix=3

        - id: product-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=3
