server:
  port: 8002

spring:
  application:
    name: item-service
  devtools:
    add-properties: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timemoutInMilliseconds: ${SERVICE_TIMEOUT:10000}

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 8000
  ReadTimeout: 10000
